credentials:
  usernames:
    Admin:
      email: jsmith@gmail.com
      name: John Smith
      password: Admin@ # To be replaced with hashed password
    BI_team:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: BI_team@ # To be replaced with hashed password
cookie:
  expiry_days: 30
  key: some_signature_key
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com
